import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard';
import MediumCard from '../components/MediumCard';
import LargeCard from '../components/LargeCard';
import Footer from '../components/Footer';

export default function Home( { exploreData,cardsData } ) {
  
  return (
    <>
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className='mx-auto max-w-7xl px-8 sm:px-16'>
        {/* Might contain items-align */}
        <section className='pt-6'>
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/* Pull Some Data From A Server --- API ENDPOINTS ALREADY MADE */}
          <div className='grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map((item,index)=>(
              <SmallCard key={index} {...item}/>
            ))}
          </div>
          
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>

          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
            {cardsData?.map((item,index)=>(
              <MediumCard key={index} {...item}/>
            ))}
          </div>
        </section>

        <section>
          <LargeCard 
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlists created by Airbnb."
            buttonText="Get Inspired"
          />
        </section>
        
      </main>

      <Footer />
      
    </>
  )
}

// SSR --- happeing at server side before sending all stuff to the user
// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
//getStaticProps always return the object and, it executes before the page component.
export async function getStaticProps() {
  const exploreData = await fetch('https://links.papareact.com/pyp').then(res=>res.json());
  
  const cardsData = await fetch('https://links.papareact.com/zp1').then(res=>res.json());

  return {
    props: {exploreData,cardsData}, // will be passed to the page component as props
  };
  
};
